- name: install ntp
  apt:
    name: ntp
    state: present

- name: template /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ntp

- name: configure timezone
  timezone:
    name: "{{ ntp_timezone }}"
